# Generated by Django 5.2.7 on 2026-01-08 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_usersettings_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='public_key',
            field=models.TextField(blank=True, help_text='Klucz publiczny RSA w formacie PEM', null=True),
        ),
    ]
