# Generated by Django 5.2.7 on 2026-01-26 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_message_is_deleted'),
        ('core', '0004_remove_message_content_message_ciphertext_and_more'),
    ]

    operations = [
    ]
